#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
THRESHOLD=80
MONTHS=1
SKIP_LOOKUP=false
MAX_LANDS=40
AVERAGE_DECK_THRESHOLD=80
java -Xmx4G -jar deckscraper.jar "$SCRIPT_DIR" $THRESHOLD $MONTHS $SKIP_LOOKUP $MAX_LANDS $AVERAGE_DECK_THRESHOLD
